#!C:\Users\proje pc 13900k\Desktop\madi_olzhas\opensmile-whisperX\venv_whisperx_clean\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
